openapi: 3.1.1
info:
    title: My API
    version: 1.0.0
    description: API documentation

paths:
    /api/health:
        get:
            summary: Health Check
            description: Returns OK if the server is healthy
            tags:
                - Health
            responses:
                "200":
                    description: Successful health check
                    content:
                        application/json:
                            schema:
                                type: object
                                properties:
                                    status:
                                        type: string
                                        example: ok
                                    success:
                                        type: boolean
                                        example: true
